// [IMP-134/IMP-297] Actionable Guidance System System & Room Dictionary Map
// SSOT definitions for lobby, network, room lifecycle, negotiation, auth & legacy aliases

import { type ActionableNotification } from './actionable_notification_gameplay.js';

export const SYSTEM_NOTIFICATIONS_MAP: Record<string, ActionableNotification> = {
  TRADE_REJECTED: {
    icon: '🤝',
    title: 'Đàm Phán Bị Từ Chối',
    description: 'Đối tác đã từ chối đề xuất đàm phán mua/bán đất!',
    tone: 'info',
    actionHint: 'Điều chỉnh điều kiện trao đổi hấp dẫn hơn và thử lại.',
  },
  ROOM_FULL: {
    icon: '🚪',
    title: 'Phòng Đã Đủ Người Chơi',
    description: 'Phòng thi đấu đã đủ 4 người chơi. Vui lòng tạo phòng mới hoặc chờ ván sau!',
    tone: 'warning',
    actionHint: 'Tạo phòng mới để bắt đầu ván đấu cùng bạn bè.',
  },
  ROOM_CODE_COLLISION: {
    icon: '⚠️',
    title: 'Mã Phòng Đã Tồn Tại',
    description: 'Mã phòng này đang được sử dụng. Vui lòng thử lại với mã phòng khác!',
    tone: 'warning',
    actionHint: 'Hệ thống sẽ tự động tạo mã phòng mới.',
  },
  SLOT_CONFLICT: {
    icon: '🪑',
    title: 'Vị Trí Đã Có Người',
    description: 'Vị trí này đã có người chơi hoặc Bot AI tiếp quản.',
    tone: 'warning',
    actionHint: 'Vui lòng chọn vị trí khác trong sảnh chờ.',
  },
  INVALID_ROOM: {
    icon: '🔍',
    title: 'Mã Phòng Không Hợp Lệ',
    description: 'Mã phòng không đúng định dạng quy định.',
    tone: 'error',
    actionHint: 'Kiểm tra lại liên kết mời hoặc mã phòng gồm 6 ký tự.',
  },
  ROOM_NOT_FOUND: {
    icon: '🔍',
    title: 'Không Tìm Thấy Phòng',
    description: 'Không tìm thấy phòng thi đấu. Vui lòng kiểm tra lại mã phòng!',
    tone: 'error',
    actionHint: 'Kiểm tra lại mã phòng hoặc tạo phòng mới.',
  },
  NOT_ENOUGH_PLAYERS: {
    icon: '👥',
    title: 'Chưa Đủ Người Chơi',
    description: 'Chưa đủ người chơi để bắt đầu. Cần tối thiểu 2 người chơi hoặc thêm Bot!',
    tone: 'info',
    actionHint: 'Mời thêm bạn bè hoặc thêm Bot AI vào phòng.',
  },
  NOT_HOST: {
    icon: '👑',
    title: 'Chỉ Chủ Phòng Mới Có Quyền',
    description: 'Chỉ chủ phòng mới có quyền thực hiện thao tác',
    tone: 'info',
    actionHint: 'Chờ chủ phòng bắt đầu trận đấu.',
  },
  ROOM_STARTED: {
    icon: '🎮',
    title: 'Phòng Thi Đấu Đã Bắt Đầu',
    description: 'Phòng này đã bắt đầu trận đấu.',
    tone: 'info',
    actionHint: 'Vui lòng chọn hoặc tạo phòng thi đấu khác.',
  },
  RATE_LIMIT_EXCEEDED: {
    icon: '🛡️',
    title: 'Thao Tác Quá Nhanh',
    description: 'Hệ thống phát hiện thao tác gửi đi quá nhanh. Vui lòng thử lại sau giây lát!',
    tone: 'error',
    actionHint: 'Chờ 1-2 giây trước khi thực hiện thao tác tiếp theo.',
  },
  PLAYER_BANKRUPT: {
    icon: '🪦',
    title: 'Người Chơi Đã Phá Sản',
    description: 'Tài khoản đã phá sản và không thể thực hiện thêm hành động trong trận đấu.',
    tone: 'error',
    actionHint: 'Bạn có thể quan sát tiếp trận đấu hoặc rời phòng.',
  },
  TOKEN_INVALID: {
    icon: '🔑',
    title: 'Phiên Đăng Nhập Hết Hạn',
    description: 'Phiên kết nối đã hết hạn hoặc không hợp lệ. Đang tự động kết nối lại...',
    tone: 'info',
    actionHint: 'Chờ hệ thống tự động làm mới phiên kết nối.',
  },
  INTENT_REJECTED: {
    icon: '⚠️',
    title: 'Hành Động Chưa Thể Thực Hiện',
    description: 'Thao tác không phù hợp với giai đoạn lượt chơi hiện tại hoặc tài sản không khả dụng.',
    tone: 'warning',
    actionHint: 'Vui lòng kiểm tra trạng thái lượt chơi hoặc bấm Kết Thúc Lượt.',
  },
  PLAYER_NOT_FOUND: {
    icon: '🔍',
    title: 'Không Tìm Thấy Người Chơi',
    description: 'Người chơi mục tiêu không tồn tại hoặc đã rời trận đấu.',
    tone: 'error',
    actionHint: 'Kiểm tra lại danh sách người chơi trong phòng.',
  },
  INVALID_PLAYER: {
    icon: '👤',
    title: 'Người Chơi Không Hợp Lệ',
    description: 'Đối tượng chỉ định không hợp lệ trong ngữ cảnh này.',
    tone: 'error',
    actionHint: 'Vui lòng chọn lại người chơi hợp lệ trong phòng.',
  },
  UNAUTHORIZED: {
    icon: '🚫',
    title: 'Không Có Quyền Thực Hiện',
    description: 'Bạn không có quyền hạn để thực thi hành động này.',
    tone: 'error',
    actionHint: 'Chỉ người chơi có quyền tương ứng mới có thể thao tác.',
  },
  INVALID_TRADE: {
    icon: '🤝',
    title: 'Đề Xuất Đàm Phán Không Hợp Lệ',
    description: 'Điều kiện trao đổi hoặc danh mục tài sản không hợp lệ.',
    tone: 'warning',
    actionHint: 'Kiểm tra lại tài sản và số tiền trong đề xuất đàm phán.',
  },
  INVALID_PRICE: {
    icon: '📉',
    title: 'Mức Giá Không Hợp Lệ',
    description: 'Mức giá đưa ra không nằm trong khung quy định của phòng chơi.',
    tone: 'warning',
    actionHint: 'Điều chỉnh lại mức giá phù hợp với quy định.',
  },
  TRADE_ALREADY_PENDING: {
    icon: '🤝',
    title: 'Đàm Phán Đang Diễn Ra',
    description: 'Phòng chơi đang có một phiên đàm phán chưa giải quyết giữa các người chơi.',
    tone: 'warning',
    actionHint: 'Vui lòng chờ phiên đàm phán hiện tại kết thúc hoặc phản hồi đề xuất.',
  },
  BOND_ALREADY_ACTIVE: {
    icon: '📜',
    title: 'Đã Có Trái Phiếu Chưa Tất Toán',
    description: 'Người chơi đang có hợp đồng trái phiếu doanh nghiệp đang hoạt động.',
    tone: 'warning',
    actionHint: 'Cần tất toán khoản nợ trái phiếu cũ trước khi phát hành mới.',
  },
  OFFER_ALREADY_RESOLVED: {
    icon: '🤝', title: 'Đề Xuất Đã Giải Quyết',
    description: 'Đề xuất giao dịch này đã được phản hồi hoặc đã hoàn tất trước đó.',
    tone: 'warning', actionHint: 'Kiểm tra biến động tài sản trên bàn cờ.',
  },
  BANKRUPT: {
    icon: '🚨', title: 'Đã Tuyên Bố Phá Sản',
    description: 'Bạn đã hoàn tất thanh lý tài sản và rời cuộc chơi.',
    tone: 'info', actionHint: 'Theo dõi ván đấu ở chế độ khán giả.',
  },
};
