// Action Reject Reason Codes — Centralized domain constants
export const ActionRejectReason = {
  GAME_NOT_STARTED: 'GAME_NOT_STARTED',
  NOT_YOUR_TURN: 'NOT_YOUR_TURN',
  INVALID_PHASE: 'INVALID_PHASE',
  FREEZE_ACTIVE: 'FREEZE_ACTIVE',
  NOT_OWNER: 'NOT_OWNER',
  HAS_BUILDING: 'HAS_BUILDING',
  ALREADY_MORTGAGED: 'ALREADY_MORTGAGED',
  NOT_MORTGAGEABLE: 'NOT_MORTGAGEABLE',
  PLAYER_NOT_FOUND: 'PLAYER_NOT_FOUND',
  NOT_MORTGAGED: 'NOT_MORTGAGED',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  INVALID_TRADE: 'INVALID_TRADE',
  INVALID_PRICE: 'INVALID_PRICE',
  PROPERTY_HAS_BUILDING: 'PROPERTY_HAS_BUILDING',
  NOT_PURCHASABLE: 'NOT_PURCHASABLE',
  PLAYER_BANKRUPT: 'PLAYER_BANKRUPT',
  PROPERTY_MORTGAGED: 'PROPERTY_MORTGAGED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  NOT_UPGRADEABLE: 'NOT_UPGRADEABLE',
  INVALID_ROOM: 'INVALID_ROOM',
} as const;

export type ActionRejectReason = (typeof ActionRejectReason)[keyof typeof ActionRejectReason];
