// [UC-GAME-038..041/MSS] Event Card Types & Constants — SSOT Enums & Tile Sets
export enum MarketCardId {
  MC_NIGHT_ECONOMY   = 'MC_NIGHT_ECONOMY',
  MC_MEGA_CONCERT    = 'MC_MEGA_CONCERT',
  MC_ALCOHOL_CHECK   = 'MC_ALCOHOL_CHECK',
  MC_CASINO_PILOT    = 'MC_CASINO_PILOT',
  MC_RATE_HIKE       = 'MC_RATE_HIKE',
  MC_CREDIT_STIMULUS = 'MC_CREDIT_STIMULUS',
  MC_LAND_FEVER      = 'MC_LAND_FEVER',
  MC_FIRE_INSPECTION = 'MC_FIRE_INSPECTION',
  MC_PUBLIC_INVEST   = 'MC_PUBLIC_INVEST',
  MC_ANTI_SPECULATE  = 'MC_ANTI_SPECULATE',
  MC_PEAK_TOURISM    = 'MC_PEAK_TOURISM',
  MC_FREEZE_TRADE    = 'MC_FREEZE_TRADE',
  MC_FUEL_SURGE      = 'MC_FUEL_SURGE',
  MC_URBAN_PLANNING  = 'MC_URBAN_PLANNING',
  MC_UTILITY_DOUBLE  = 'MC_UTILITY_DOUBLE',
  MC_COASTAL_STORM   = 'MC_COASTAL_STORM',
}

export enum ChanceCardId {
  CC_PLATE_AUCTION    = 'CC_PLATE_AUCTION',
  CC_TAX_AUDIT        = 'CC_TAX_AUDIT',
  CC_STOCK_PROFIT     = 'CC_STOCK_PROFIT',
  CC_DIPLOMATIC       = 'CC_DIPLOMATIC',
  CC_CONTRACT_PENALTY = 'CC_CONTRACT_PENALTY',
  CC_LAND_CHANGE      = 'CC_LAND_CHANGE',
  CC_BUILD_HALT       = 'CC_BUILD_HALT',
  CC_MA_FORCE         = 'CC_MA_FORCE',
  CC_COPYRIGHT        = 'CC_COPYRIGHT',
  CC_OVERDRAFT        = 'CC_OVERDRAFT',
  CC_JUNK_STOCK       = 'CC_JUNK_STOCK',
  CC_FRANCHISE        = 'CC_FRANCHISE',
  CC_LAND_RECLAIM     = 'CC_LAND_RECLAIM',
  CC_VENUE_INCIDENT   = 'CC_VENUE_INCIDENT',
  CC_CONCERT_SPONSOR  = 'CC_CONCERT_SPONSOR',
  CC_FREE_CREDIT      = 'CC_FREE_CREDIT',
  CC_PORT_EXCLUSIVE   = 'CC_PORT_EXCLUSIVE',
  CC_SLOW_BUILD       = 'CC_SLOW_BUILD',
  CC_MEDIA_CRISIS     = 'CC_MEDIA_CRISIS',
  CC_SWAP_PROJECT     = 'CC_SWAP_PROJECT',
}

export const RESORT_CELLS      = [11, 13, 14, 21, 24, 29] as const;
export const COASTAL_CELLS     = [11, 14, 16, 18, 19] as const;
export const SERVICE_CELLS     = [6, 8, 26, 27] as const;
export const INFRA_CELLS       = [5, 15, 25, 35] as const;
export const UTILITY_CELLS     = [12, 28] as const;
export const HANOI_HCMC_CELLS  = [31, 32, 34, 37, 39] as const;
export const LAND_FEVER_CELLS  = [6, 8, 31] as const;

export const HOSE_OUTCOMES: Readonly<Record<number, number>> = {
  1: 0.50, 2: 0.75, 3: 1.00, 4: 1.20, 5: 1.50, 6: 2.00,
};
